export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGINING = "LOGINING";
export const LOADING_CURRENT_USER= "LOADING_CURRENT_USER";
export const LOADING_CURRENT_USER_SUCCESS = "LOADING_CURRENT_USER_SUCCESS";
export const LOADING_CURRENT_USER_FAIL = "LOADING_CURRENT_USER_FAIL";
export const LOG_OUT = "LOG_OUT";
export const ERRORBASE="ERRORBASE";